### ISSUE TITLE
Tooltips - Won't work on elements that already have pseudo elements. 

### ISSUE THREAD

**Issue by fleeting** [Monkee-Boy/jubilee#7]
The tooltips make use of pseudo elements which means they won't work if pseudo are already being used on the element. Need some ideas for a work around or if this is acceptable to keep these tooltips simple.

**Comment by fleeting** [comment]
I'm actually okay with this limitation but open to ideas. Maybe a js fallback when we need it?

**Comment by djsaun** [comment]
I'm okay with this limitation too. I imagine that the most common use case for these tooltips will be individual words or phrases (as opposed to buttons), so more than likely we wouldn't already have psuedoelements applied to these elements.

**Comment by defvayne23** [comment]
I think it's fine as is. If we did create a data attribute, the before/after element would still need to over style the styles of the tooltip. I think it would be easier to work around the tooltip by adding a span that we add style to instead.

**Comment by fleeting** [comment]
Perfect, thanks guys! Closing this.
